### ISSUE TITLE
Pointless repository?

### ISSUE THREAD

**Issue by GameGlitz** [CCBlueX/LiquidBounce-Donate#1]
This repo is empty, is it going to be removed or is it fresh for an upcoming donation page (which I would love to see coming :eyes:)

**Comment by SenkJu** [comment]
The only purpose of this repository is to redirect https://donate.liquidbounce.net to https://liquidbounce.net/donate. We could probably do it differently.

**Comment by GameGlitz** [comment]
If you guys are using cloudflare a page rule is possible, otherwise I'd just make a branch on the site repo to keep things in one place.

To use a page rule, make a dummy A record to something like 192.0.1.0 and then just make a forwarding URL set to permanent in page rules.

**Comment by SenkJu** [comment]
We are already using all page rules we have with the free plan. Also, what site repository are you referring to?

**Comment by GameGlitz** [comment]
I'm not aware if it's open source, however I was referring to if there was one.

**Comment by GameGlitz** [comment]
> We are already using all page rules we have with the free plan. Also, what site repository are you referring to?

In that case, it makes sense. I'd make a quick description to the repo to prevent people like me nitpicking haha

**Comment by SenkJu** [comment]
The website isn't open source and GitHub pages only allows one branch to be used anyway to my knowledge. We could host this site on our webserver too. The sole reason this repository still exists is that I couldn't be bothered yet to move it.

**Comment by GameGlitz** [comment]
Speaking of - I'd honestly love to see a Jamstack based site for LiquidBounce in the future. It would render things like this a lot less messy and improve the site usability for the future of having sharable scripts, which speaking of, should probably have categories / tags before it becomes a pain to find what you want.

I'm not gonna say this is needed though as the site currently is so small it essentially feels asynchronous to use, just because of how fast everything is.
